### ISSUE TITLE
bug: nginx config + certbot script are fucked up

### ISSUE THREAD

**Issue by bogdzn** [ARKultur/sentinel#1]
had to setup an nginx config locally + local certbot, we should fix that for next sprint because it's annoying as fuck:

- use a more robust python script (can be inspired from the bash thing we currently have)
- back-end takes too long to start-up, which times out the verification from the certbot thing, so either implement a kind of wait-for-it for the back-end or have the back-end dockerfile build a binary which boots up instantly

**Comment by Alvarwow69** [comment]
We don't use nginx anymore

**Comment by djnnvx** [comment]
good to know
